### ISSUE TITLE
NoClassDefFoundError when using google-cloud-spanner 6.28.0

### ISSUE THREAD

**Issue by SanjayVas** [cloudspannerecosystem/liquibase-spanner#120]
Possibly related to #118. I updated google-cloud-spanner from 6.23.3 to 6.28.0, google-cloud-spanner-jdbc from 2.6.4 to 2.7.6, and liquibase-spanner from 4.6.1 to 4.10.0.

I get the following error:

```
java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.spanner.TimestampBound
        at com.google.cloud.spanner.connection.ConnectionImpl.<init>(ConnectionImpl.java:213)
        at com.google.cloud.spanner.connection.ConnectionOptions.getConnection(ConnectionOptions.java:890)
        at com.google.cloud.spanner.jdbc.AbstractJdbcConnection.<init>(AbstractJdbcConnection.java:65)
        at com.google.cloud.spanner.jdbc.JdbcConnection.<init>(JdbcConnection.java:56)
        at com.google.cloud.spanner.jdbc.JdbcDriver.connect(JdbcDriver.java:196)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251
```

**Comment by SanjayVas** [comment]
This may be a google-cloud-spanner-jdbc issue.

**Comment by olavloite** [comment]
Closing as https://github.com/googleapis/java-spanner-jdbc/issues/939 was closed. Please re-open if this did not fix the problem when working with Liquibase.
