### ISSUE TITLE
NullPointerException caused by index

### ISSUE THREAD

**Issue by hanikesn** [cloudspannerecosystem/liquibase-spanner#159]
The following test case causes a NullPointerException when generating a Changelog:

<details><summary>Stacktrace</summary>

```
[liquibase.integration] Cannot invoke "java.lang.Short.shortValue()" because the return value of "liquibase.snapshot.CachedRow.getShort(String)" is null
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException: Cannot invoke "java.lang.Short.shortValue()" because the return value of "liquibase.snapshot.CachedRow.getShort(String)" is null
        at liquibase.command.CommandScope.execute(CommandScope.java:179)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:54)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:23)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:353)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:318)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException: Cannot invoke "java.lang.Short.shortValue()" because the return value of "liquibase.snapshot.CachedRow.getShort(String)" is null
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:260)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1585)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:394)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:393)
        at liquibase.integration.commandline.Main$1.run(Main.java:215)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:215)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
        at liquibase.command.CommandScope.execute(CommandScope.java:173)
        ... 18 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException: Cannot invoke "java.lang.Short.shortValue()" because the return value of "liquibase.snapshot.CachedRow.getShort(String)" is null
        at liquibase.command.CommandScope.execute(CommandScope.java:179)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:258)
        ... 31 more
Caused by: liquibase.exception.DatabaseException: java.lang.NullPointerException: Cannot invoke "java.lang.Short.shortValue()" because the return value of "liquibase.snapshot.CachedRow.getShort(String)" is null
        at liquibase.snapshot.jvm.IndexSnapshotGenerator.snapshotObject(IndexSnapshotGenerator.java:304)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:66)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69)
        at liquibase.ext.spanner.snapshotgenerator.ForeignKeySnapshotGeneratorSpanner.snapshot(ForeignKeySnapshotGeneratorSpanner.java:48)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:445)
        at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:373)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:335)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:445)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:467)
        at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:373)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:335)
        at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105)
        at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58)
        at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:188)
        at liquibase.command.core.InternalDiffCommandStep.createReferenceSnapshot(InternalDiffCommandStep.java:188)
        at liquibase.command.core.InternalDiffCommandStep.createDiffResult(InternalDiffCommandStep.java:98)
        at liquibase.command.core.InternalGenerateChangelogCommandStep.run(InternalGenerateChangelogCommandStep.java:67)
        at liquibase.command.CommandScope.execute(CommandScope.java:173)
        ... 32 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Short.shortValue()" because the return value of "liquibase.snapshot.CachedRow.getShort(String)" is null
        at liquibase.snapshot.jvm.IndexSnapshotGenerator.snapshotObject(IndexSnapshotGenerator.java:189)
        ... 56 more
```
</details>

### Test Case

Versions:
- Liquibase Version: 4.17.2
- Liquibase Community 4.17.2 by Liquibase
- liquibase-spanner-4.17.0-all.jar

`liquibase  generateChangeLog --diff-types="indexes" --log-level 1`

```
CREATE TABLE TestTable (
                                    driver_id STRING(256) NOT NULL,
                                    event_id STRING(256) NOT NULL,
                                    partner_id STRING(256) NOT NULL,
                                    event_time TIMESTAMP NOT NULL,
                                    event_type STRING(256) NOT NULL,
) PRIMARY KEY(event_id, partner_id), ROW DELETION POLICY (OLDER_THAN(event_time, INTERVAL 27 DAY));

CREATE NULL_FILTERED INDEX TestIndex ON TestTable(event_id, partner_id, event_type) STORING (driver_id, event_time);
```

Thanks!

**Comment by hanikesn** [comment]
Thanks!
